# Generated by Django 5.0.2 on 2024-03-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsagencyAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.CharField(choices=[('pol', 'Politics'), ('art', 'Art'), ('tech', 'Tech'), ('trivia', 'Trivial News')], max_length=6),
        ),
        migrations.AlterField(
            model_name='story',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='details',
            field=models.CharField(max_length=256),
        ),
    ]
